const ranges=[
{id:1,brands:['Apple', 'Dell', 'HP', 'Lenovo', 'ASUS'],image:'assets/category-6683410.jpg',types:['Everyday laptops', '2-in-1 laptops', 'Gaming laptops'],name:'Laptops',group:'Computing',price:'$299–$1,299',desc:'For coursework, everyday tasks and getting things done.',symbol:'⌨'},
{id:2,brands:['Alienware', 'ASUS ROG', 'MSI', 'CyberPowerPC'],image:'assets/category-30265371.jpg',types:['Gaming desktops', 'Compact gaming PCs', 'Monitors & peripherals'],name:'Gaming PCs',group:'Computing',price:'Ask for pricing',desc:'Build your next setup around the way you play.',symbol:'▣'},
{id:3,brands:['DJI', 'Holy Stone', 'Potensic'],image:'assets/category-724921.jpg',types:['Camera drones', 'Mini drones', 'Foldable drones'],name:'Drones',group:'Entertainment',price:'$99–$249',desc:'Explore a new perspective from above.',symbol:'✣'},
{id:4,brands:['SanDisk', 'Kingston', 'Samsung', 'PNY'],image:'assets/category-18641665.jpg',types:['USB-A drives', 'USB-C drives', 'Dual-connector drives'],name:'USB Flash Drives',group:'Everyday',price:'$9–$49',desc:'Keep projects, photos and everyday files close.',symbol:'▰'},
{id:5,brands:['Amazon Echo', 'Google Nest', 'Philips Hue', 'TP-Link Tapo'],image:'assets/category-977296.jpg',types:['Smart speakers', 'Smart lighting', 'Smart plugs'],name:'Smart Home Devices',group:'Everyday',price:'$29–$199',desc:'Make your home a little more connected.',symbol:'⌂'},
{id:6,brands:['Samsung', 'LG', 'Sony', 'TCL'],image:'assets/category-1827054.jpg',types:['Smart TVs', '4K TVs', 'Compact TVs'],name:'TVs',group:'Entertainment',price:'Ask for pricing',desc:'Find a screen for family nights and favorite shows.',symbol:'▱'},
{id:7,brands:['Anker', 'Belkin', 'OtterBox', 'Spigen'],image:'assets/category-8004014.jpg',types:['Phone cases', 'Charging cables', 'Power banks', 'Screen protectors'],name:'Mobile Accessories',group:'Everyday',price:'Ask for pricing',desc:'Everyday essentials for your mobile devices.',symbol:'▯'}];
const state={orders:[],bookings:[]};let selected=new Set(),bag=[];const $=s=>document.querySelector(s);const modal=$('#modal');
function show(html){$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal()}
$('.close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});
function render(filter='All'){ $('#products').innerHTML=ranges.filter(p=>filter==='All'||p.group===filter).map(p=>`<article class="product"><div class="product-art"><img src="${p.image}" alt="${p.name} category photograph" loading="lazy" width="800" height="600"></div><h3>${p.name}</h3><p>${p.desc}</p><div class="device-types"><h4>Devices & Accessories</h4><ul>${p.types.map(t=>`<li>${t.replace(/\b[a-z]/g,c=>c.toUpperCase())}</li>`).join('')}</ul><h4 class="brand-heading">Brands</h4><div class="brand-list">${p.brands.map(b=>`<span>${b}</span>`).join('')}</div></div><strong>${p.price}</strong><div class="product-actions"><label><input type="checkbox" data-id="${p.id}" ${selected.has(p.id)?'checked':''}> Compare</label><button data-add="${p.id}">${bag.includes(p.id)?'Saved':'Save to bag'}</button></div></article>`).join('');
$('#products').querySelectorAll('input').forEach(i=>i.onchange=()=>{const id=Number(i.dataset.id);if(i.checked&&selected.size===3){i.checked=false;show('<h2>Compare up to three ranges</h2><p>Remove a selection before adding another.</p>');return}i.checked?selected.add(id):selected.delete(id);$('#compare-count').textContent=`${selected.size} ranges selected`});
$('#products').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{let id=Number(b.dataset.add);if(!bag.includes(id))bag.push(id);$('#count').textContent=bag.length;b.textContent='Saved'});}
$('.filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('.filters .active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)});
$('#compare').onclick=()=>{if(selected.size<2){show('<h2>Choose two or three ranges</h2><p>Select Compare on the categories you want to explore.</p>');return}const ps=ranges.filter(p=>selected.has(p.id));show(`<h2>Compare product ranges</h2><div style="overflow:auto"><table><thead><tr><th>Range</th>${ps.map(p=>`<th><img class="compare-photo" src="${p.image}" alt="${p.name}">${p.name}</th>`).join('')}</tr></thead><tbody><tr><th>Price range</th>${ps.map(p=>`<td>${p.price}</td>`).join('')}</tr><tr><th>Brands</th>${ps.map(p=>`<td>${p.brands.join(', ')}</td>`).join('')}</tr><tr><th>Good for</th>${ps.map(p=>`<td>${p.desc}</td>`).join('')}</tr></tbody></table></div><p>Compare category pricing, brands and uses to find your next upgrade.</p>`)};
function activeFilter(){return $('.filters .active').dataset.filter}
function bagView(){show(`<h2>Your Bag</h2>${bag.length?`<ul class="bag-list">${bag.map(id=>{const p=ranges.find(p=>p.id===id);return `<li><span>${p.name}<small>${p.price}</small></span><button data-remove="${id}">Remove</button></li>`}).join('')}</ul><button id="checkout" class="button">Request These Items</button><button id="clear-bag">Clear Bag</button>`:'<p>Your bag is empty. Browse the collection to save your favorite tech.</p><button data-close class="button">Continue Shopping</button>'}`)}
$('#bag').onclick=bagView;
$('#modal-content').addEventListener('click',e=>{
 if(e.target.hasAttribute('data-close'))modal.close();
 if(e.target.dataset.remove){bag=bag.filter(id=>id!==Number(e.target.dataset.remove));$('#count').textContent=bag.length;render(activeFilter());bagView()}
 if(e.target.id==='clear-bag'){bag=[];$('#count').textContent=0;render(activeFilter());bagView()}
 if(e.target.id==='checkout'){show(`<h2>Request Your Tech</h2><p>Tell us how to reach you to confirm your selected items and pricing.</p><form id="order-form">${contactFields()}<label>Pickup or delivery<select name="fulfillment"><option>Curbside Pickup</option><option>In-Store Pickup</option><option>Delivery</option></select></label><button class="button">Submit Request</button></form>`);$('#order-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id='TH-'+String(state.orders.length+1001);state.orders.push({id,items:bag.map(i=>ranges.find(p=>p.id===i).name),fulfillment:f.get('fulfillment'),status:'Request Received'});bag=[];$('#count').textContent=0;render(activeFilter());show(`<h2>Request Received</h2><p>Your reference is <strong>${id}</strong>. Use Order Tracking to see your request status.</p><button data-close class="button">Continue Shopping</button>`)}}
});
function contactFields(){return '<label>Your name<input name="name" autocomplete="name" required maxlength="100"></label><label>Email address<input name="email" type="email" autocomplete="email" required maxlength="200"></label>'}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const windows=[{start:10,label:'10:00 AM – 12:00 PM'},{start:12,label:'12:00 PM – 2:00 PM'},{start:14,label:'2:00 PM – 4:00 PM'},{start:16,label:'4:00 PM – 6:00 PM'}];
$('#appointment').onclick=()=>{
 show(`<h2>Book a Support Visit</h2><p>Choose a service, date and two-hour arrival window.</p><form id="visit"><label>Service<select name="service"><option>Device Setup</option><option>Repair & Troubleshooting</option><option>Extended Warranty Consultation</option></select></label><label>Visit date<input type="date" name="date" id="date" required></label><fieldset class="time-slots"><legend>Available Arrival Windows</legend><div id="slots"></div></fieldset>${contactFields()}<label>Device / issue<textarea name="issue" rows="3" maxlength="1000" placeholder="Tell us what you need help with"></textarea></label><button class="button">Book Visit</button><p id="visit-error" role="status"></p></form>`);
 const date=$('#date');date.min=iso(new Date());date.value=date.min;
 function slots(){const now=new Date();$('#slots').innerHTML=windows.map(w=>{const start=new Date(date.value+'T'+String(w.start).padStart(2,'0')+':00:00');const unavailable=start<=now||state.bookings.some(b=>b.date===date.value&&b.start===w.start);return `<label class="slot ${unavailable?'unavailable':''}"><input type="radio" name="window" value="${w.start}" required ${unavailable?'disabled':''}>${w.label}${unavailable?' · Unavailable':''}</label>`}).join('')}
 date.onchange=slots;slots();$('#visit').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),day=f.get('date'),start=Number(f.get('window'));if(!day||new Date(day+'T'+String(start).padStart(2,'0')+':00:00')<=new Date()||state.bookings.some(b=>b.date===day&&b.start===start)){slots();$('#visit-error').textContent='Please select an available future window.';return}const id='SV-'+(state.bookings.length+1001);state.bookings.push({id,date:day,start,service:f.get('service')});const display=new Date(day+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});show(`<h2>Your Visit Is Booked</h2><p><strong>${f.get('service')}</strong><br>${display}<br>${windows.find(w=>w.start===start).label}</p><p>Booking reference: <strong>${id}</strong>. Bring your device and any relevant accessories.</p><button data-close class="button">Done</button>`)}}
$('#customer-support').onclick=()=>{show(`<h2>Customer Support</h2><p>Send your question to our team at support@techhubelectronics.com.</p><form id="email-form">${contactFields()}<label>Subject<input name="subject" required maxlength="150"></label><label>Message<textarea name="message" required rows="5" maxlength="3000"></textarea></label><button class="button">Send Message</button></form>`);$('#email-form').onsubmit=e=>{e.preventDefault();show('<h2>Message Received</h2><p>Thank you for contacting TechHub Electronics. Our team will follow up about your question.</p><button data-close class="button">Done</button>')}};
$('#student-info').onclick=()=>{show(`<h2>Student Savings</h2><p>Check your student email to unlock savings on your next upgrade.</p><form id="student-form"><label>Student email<input name="email" type="email" required placeholder="you@college.edu"></label><button class="button">Check Eligibility</button><p id="student-result" role="status"></p></form>`);$('#student-form').onsubmit=e=>{e.preventDefault();const email=new FormData(e.target).get('email');$('#student-result').textContent=/@[^@]+\.edu$/i.test(email)?'Student eligibility confirmed. Mention STUDENT at pickup to ask about available discounts.':'Please use your college or university .edu email address.'}};
$('#tracking').onclick=()=>{show(`<h2>Order Tracking</h2><p>Enter your request reference, or try TH-DEMO to explore tracking.</p><form id="tracking-form"><label>Order / request reference<input name="reference" required placeholder="TH-1001"></label><button class="button">Track Order</button></form><div id="tracking-result" role="status"></div>`);$('#tracking-form').onsubmit=e=>{e.preventDefault();const id=new FormData(e.target).get('reference').trim().toUpperCase(),order=id==='TH-DEMO'?{id,status:'Ready for Pickup',items:['Laptop','USB Flash Drive'],fulfillment:'Curbside Pickup'}:state.orders.find(o=>o.id===id);$('#tracking-result').textContent=order?`${order.id}: ${order.status}. ${order.items.join(', ')}. ${order.fulfillment}.`:'We could not find that reference. Check the number and try again.'}};render();

const chatHistory=[{who:'support',text:'Hi! I’m TechHub’s virtual support assistant. Ask about products, pickup, repairs or booking a support visit.'}];
function chatReply(message){const m=message.toLowerCase();if(/book|appointment|schedule|visit/.test(m))return 'Choose Plan a support visit to select your service, date and a two-hour arrival window. You’ll receive a booking reference.';if(/repair|broken|fix|setup|set up|troubleshoot/.test(m))return 'We help with device setup, repairs and troubleshooting. Book a support visit and tell us about your device and issue.';if(/student|discount|college/.test(m))return 'Use Explore student savings to check your college .edu email and ask about student discounts at pickup.';if(/pickup|delivery|shipping/.test(m))return 'Save your selected categories to your bag, then request your items and choose curbside pickup, in-store pickup or delivery.';if(/order|track|reference/.test(m))return 'Use Order tracking with your TH request reference. You can also try TH-DEMO to view a ready-for-pickup order.';if(/price|cost|usb|flash/.test(m))return 'USB Flash Drives range from $9–$49, Laptops $299–$1,299, Drones $99–$249 and Smart Home Devices $29–$199. Select categories and click Compare selected for a closer look.';if(/laptop|gaming|drone|tv|brand|accessor|screen|product/.test(m))return 'Browse our seven categories for devices, accessories and brands. Mobile Accessories includes phone cases, cables, power banks and screen protectors. Save your favorites to your bag.';if(/email|human|agent|contact/.test(m))return 'Choose Customer Support to send an on-site message to support@techhubelectronics.com.';if(/hello|hi\b|thanks|thank/.test(m))return 'Happy to help! What would you like to know about shopping or tech support?';return 'I can help with products, prices, pickup, student discounts, order tracking or support appointments. For a specific question, use Customer Support to message our team.'}
function paintChat(){const log=$('#chat-log');log.innerHTML='';chatHistory.forEach(m=>{const bubble=document.createElement('div');bubble.className='chat-bubble '+m.who;const label=document.createElement('strong');label.textContent=m.who==='support'?'TechHub Assistant':'You';const text=document.createElement('p');text.textContent=m.text;bubble.append(label,text);log.append(bubble)});log.scrollTop=log.scrollHeight}
$('#chat-support').onclick=()=>{show('<h2>Chat With Support</h2><p class="chat-caption">TechHub Virtual Assistant</p><div id="chat-log" role="log" aria-live="polite" aria-label="Support conversation"></div><form id="chat-form"><label>Your message<input id="chat-message" name="message" placeholder="How can we help?" required maxlength="1000" autocomplete="off"></label><button class="button">Send</button></form>');paintChat();$('#chat-form').onsubmit=e=>{e.preventDefault();const input=$('#chat-message'),message=input.value.trim();if(!message)return;chatHistory.push({who:'you',text:message},{who:'support',text:chatReply(message)});paintChat();input.value='';input.focus()}};
