const ranges=[
{id:1,brands:['Apple', 'Dell', 'HP', 'Lenovo', 'ASUS'],image:'assets/category-6683410.jpg',types:['Everyday laptops', '2-in-1 laptops', 'Gaming laptops'],name:'Laptops',group:'Computing',price:'$299–$1,299',desc:'For coursework, everyday tasks and getting things done.',symbol:'⌨'},
{id:2,brands:['Alienware', 'ASUS ROG', 'MSI', 'CyberPowerPC'],image:'assets/category-30265371.jpg',types:['Gaming desktops', 'Compact gaming PCs', 'Monitors & peripherals'],name:'Gaming PCs',group:'Computing',price:'Ask for pricing',desc:'Build your next setup around the way you play.',symbol:'▣'},
{id:3,brands:['DJI', 'Holy Stone', 'Potensic'],image:'assets/category-724921.jpg',types:['Camera drones', 'Mini drones', 'Foldable drones'],name:'Drones',group:'Entertainment',price:'$99–$249',desc:'Explore a new perspective from above.',symbol:'✣'},
{id:4,brands:['SanDisk', 'Kingston', 'Samsung', 'PNY'],image:'assets/category-18641665.jpg',types:['USB-A drives', 'USB-C drives', 'Dual-connector drives'],name:'USB Flash Drives',group:'Everyday',price:'$9–$49',desc:'Keep projects, photos and everyday files close.',symbol:'▰'},
{id:5,brands:['Amazon Echo', 'Google Nest', 'Philips Hue', 'TP-Link Tapo'],image:'assets/category-977296.jpg',types:['Smart speakers', 'Smart lighting', 'Smart plugs'],name:'Smart Home Devices',group:'Everyday',price:'$29–$199',desc:'Make your home a little more connected.',symbol:'⌂'},
{id:6,brands:['Samsung', 'LG', 'Sony', 'TCL'],image:'assets/category-1827054.jpg',types:['Smart TVs', '4K TVs', 'Compact TVs'],name:'TVs',group:'Entertainment',price:'Ask for pricing',desc:'Find a screen for family nights and favorite shows.',symbol:'▱'},
{id:7,brands:['Anker', 'Belkin', 'OtterBox', 'Spigen'],image:'assets/category-8004014.jpg',types:['Phone cases', 'Charging cables', 'Power banks', 'Screen protectors'],name:'Mobile Accessories',group:'Everyday',price:'Ask for pricing',desc:'Everyday essentials for your mobile devices.',symbol:'▯'}];
// Fictional device models and specifications for the class demonstration.
const specs=[
 [['StudyBook 14',399,{Processor:'Quad-Core',Memory:'8 GB',Storage:'256 GB SSD',Display:'14-inch Full HD'}],['FlexBook 15',799,{Processor:'Six-Core',Memory:'16 GB',Storage:'512 GB SSD',Display:'15.6-inch Full HD'}]],
 [['GameStation Core',899,{Processor:'Six-Core',Memory:'16 GB',Storage:'512 GB SSD',Graphics:'6 GB Dedicated'}],['GameStation Pro',1299,{Processor:'Eight-Core',Memory:'32 GB',Storage:'1 TB SSD',Graphics:'8 GB Dedicated'}]],
 [['SkyView Mini',99,{Camera:'1080p',Flight:'15 Minutes',Range:'100 Meters',Design:'Compact'}],['SkyView Fold',249,{Camera:'4K',Flight:'25 Minutes',Range:'500 Meters',Design:'Foldable'}]],
 [['PocketDrive 32',9,{Capacity:'32 GB',Connector:'USB-A',Interface:'USB 2.0',Design:'Compact'}],['PocketDrive Duo 128',29,{Capacity:'128 GB',Connector:'USB-A / USB-C',Interface:'USB 3.0',Design:'Dual Connector'}]],
 [['HomeLink Plug',29,{Connection:'Wi-Fi',Control:'App / Voice',Purpose:'Outlet Control',Power:'Wall Outlet'}],['HomeLink Speaker',99,{Connection:'Wi-Fi / Bluetooth',Control:'Voice / App',Purpose:'Audio / Assistant',Power:'AC Adapter'}]],
 [['ViewScreen 43',299,{Size:'43 Inches',Resolution:'4K',Connectivity:'Wi-Fi / HDMI',Features:'Smart Streaming'}],['ViewScreen 55',499,{Size:'55 Inches',Resolution:'4K',Connectivity:'Wi-Fi / HDMI',Features:'Smart Streaming / HDR'}]],
 [['ClearGuard Protector',15,{Compatibility:'Selected Smartphones',Material:'Tempered Glass',Purpose:'Screen Protection',Contents:'Protector / Installation Kit'}],['PowerGo 10000',29,{Compatibility:'USB Devices',Capacity:'10,000 mAh',Purpose:'Portable Charging',Connection:'USB-A / USB-C'}]]
];
const devices=specs.flatMap((rows,k)=>rows.map((r,j)=>({id:(k+1)*10+j,name:'TechHub '+r[0],price:r[1],spec:r[2],category:k+1,image:ranges[k].image})));
const state={orders:[],bookings:[],studentVerified:false};let selected=new Set(),bag=[];const $=s=>document.querySelector(s);const modal=$('#modal');const money=n=>'$'+n.toFixed(2);
function show(html){$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal()}
$('.close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});
function render(filter='All'){ $('#products').innerHTML=ranges.filter(p=>filter==='All'||p.group===filter).map(p=>`<article class="product"><div class="product-art"><img src="${p.image}" alt="${p.name} category photograph" loading="lazy" width="800" height="600"></div><h3>${p.name}</h3><p>${p.desc}</p><div class="device-types"><h4>Devices & Accessories</h4><ul>${p.types.map(t=>`<li>${t.replace(/\b[a-z]/g,c=>c.toUpperCase())}</li>`).join('')}</ul><h4 class="brand-heading">Brands</h4><div class="brand-list">${p.brands.map(b=>`<span>${b}</span>`).join('')}</div></div><strong>${p.price}</strong><div class="product-actions"><button data-browse="${p.id}">Shop & Compare Devices</button></div></article>`).join('');$('#products').querySelectorAll('[data-browse]').forEach(b=>b.onclick=()=>deviceView(Number(b.dataset.browse)))}
$('.filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('.filters .active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)});
function deviceView(category){const cat=ranges.find(r=>r.id===category);selected.clear();$('#compare-count').textContent='0 devices selected';show(`<h2>${cat.name}</h2><p class="fine">TechHub demonstration models with fictional specifications and prices. Photos represent the category.</p><div class="device-grid">${devices.filter(d=>d.category===category).map(d=>`<article><h3>${d.name}</h3><strong>${money(d.price)}</strong><dl>${Object.entries(d.spec).map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('')}</dl><label><input type="checkbox" data-device="${d.id}"> Compare Device</label><button data-device-add="${d.id}" class="button">Add to Bag</button></article>`).join('')}</div><button id="device-compare" class="button">Compare Devices</button><p id="device-error" role="status"></p>`);$('#modal-content').querySelectorAll('[data-device]').forEach(i=>i.onchange=()=>{i.checked?selected.add(Number(i.dataset.device)):selected.delete(Number(i.dataset.device));$('#compare-count').textContent=`${selected.size} devices selected`})}
function compareDevices(){if(selected.size<2){$('#device-error').textContent='Select two devices to compare.';return}const ds=devices.filter(d=>selected.has(d.id)),keys=[...new Set(ds.flatMap(d=>Object.keys(d.spec)))];show(`<h2>Compare Devices</h2><div class="table-scroll"><table><thead><tr><th>Device</th>${ds.map(d=>`<th>${d.name}</th>`).join('')}</tr></thead><tbody><tr><th>Price</th>${ds.map(d=>`<td>${money(d.price)}</td>`).join('')}</tr>${keys.map(k=>`<tr><th>${k}</th>${ds.map(d=>`<td>${d.spec[k]||'Not Applicable'}</td>`).join('')}</tr>`).join('')}<tr><th>Shop</th>${ds.map(d=>`<td><button data-device-add="${d.id}">Add to Bag</button></td>`).join('')}</tr></tbody></table></div><p class="fine">Fictional TechHub models for the assignment.</p>`)}
$('#compare').onclick=()=>{if(selected.size>=2){compareDevices();return}show(`<h2>Choose a Category to Compare</h2><p>Select individual devices with prices and specifications.</p>${ranges.map(r=>`<button data-browse="${r.id}">${r.name}</button>`).join('')}`)};
function activeFilter(){return $('.filters .active').dataset.filter}
function totals(){const subtotal=bag.reduce((n,id)=>n+devices.find(d=>d.id===id).price,0),discount=state.studentVerified?subtotal*.1:0;return {subtotal,discount,total:subtotal-discount}}
function bagView(){const t=totals();show(`<h2>Your Bag</h2>${bag.length?`<ul class="bag-list">${bag.map((id,k)=>{const d=devices.find(d=>d.id===id);return `<li><span>${d.name}<small>${money(d.price)}</small></span><button data-remove="${k}">Remove</button></li>`}).join('')}</ul><p>Subtotal: ${money(t.subtotal)}<br>Student Savings: −${money(t.discount)}<br><strong>Total: ${money(t.total)}</strong></p><button id="checkout" class="button">Secure Checkout Demo</button><button id="clear-bag">Clear Bag</button>`:'<p>Your bag is empty. Shop a category to add a device.</p><button data-close class="button">Continue Shopping</button>'}`)}
$('#bag').onclick=bagView;
function checkout(){if(!bag.length){bagView();return}const t=totals();show(`<h2>Secure Checkout Demonstration</h2><p class="fine">No real payment is collected. Use the provided test payment method.</p><form id="order-form">${contactFields()}<label>Fulfillment<select name="fulfillment" id="fulfillment"><option>Curbside Pickup</option><option>In-Store Pickup</option><option>Delivery</option></select></label><div id="delivery-fields" hidden><label>Delivery address<textarea name="address" id="delivery-address" rows="2"></textarea></label></div><label>Payment method<select name="payment"><option>Demo Card •••• 4242</option><option>Demo Digital Wallet</option></select></label><p>Subtotal: ${money(t.subtotal)}<br>Student discount: −${money(t.discount)}<br>Delivery: Free<br>Demo tax: $0.00<br><strong>Total: ${money(t.total)}</strong></p><label><input type="checkbox" name="consent" required> I understand this is a simulated purchase with no charge.</label><button class="button">Place Demo Order</button></form>`);$('#fulfillment').onchange=()=>{const delivery=$('#fulfillment').value==='Delivery';$('#delivery-fields').hidden=!delivery;$('#delivery-address').required=delivery};$('#order-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(!bag.length)return;if(f.get('fulfillment')==='Delivery'&&!String(f.get('address')).trim())return;const id='TH-'+String(state.orders.length+1001);state.orders.push({id,items:bag.map(i=>devices.find(d=>d.id===i).name),fulfillment:f.get('fulfillment'),status:'Order Confirmed',total:t.total});bag=[];$('#count').textContent=0;render(activeFilter());show(`<h2>Order Confirmed</h2><p>Demo order <strong>${id}</strong><br>Total: ${money(t.total)}<br>No payment was charged.</p><p>Use Order Tracking to view your order.</p><button data-close class="button">Continue Shopping</button>`)}}
$('#modal-content').addEventListener('click',e=>{const b=e.target;if(b.hasAttribute('data-close'))modal.close();if(b.dataset.browse)deviceView(Number(b.dataset.browse));if(b.dataset.deviceAdd){bag.push(Number(b.dataset.deviceAdd));$('#count').textContent=bag.length;b.textContent='Added to Bag'}if(b.id==='device-compare')compareDevices();if(b.dataset.remove!==undefined){bag.splice(Number(b.dataset.remove),1);$('#count').textContent=bag.length;bagView()}if(b.id==='clear-bag'){bag=[];$('#count').textContent=0;bagView()}if(b.id==='checkout')checkout()});
function contactFields(){return '<label>Your name<input name="name" autocomplete="name" required maxlength="100"></label><label>Email address<input name="email" type="email" autocomplete="email" required maxlength="200"></label>'}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const windows=[{start:10,label:'10:00 AM – 12:00 PM'},{start:12,label:'12:00 PM – 2:00 PM'},{start:14,label:'2:00 PM – 4:00 PM'},{start:16,label:'4:00 PM – 6:00 PM'}];
$('#appointment').onclick=()=>{
 show(`<h2>Book a Support Visit</h2><p>Choose a service, date and two-hour arrival window.</p><form id="visit"><label>Service<select name="service"><option>Device Setup</option><option>Repair & Troubleshooting</option><option>Extended Warranty Consultation</option></select></label><label>Visit date<input type="date" name="date" id="date" required></label><fieldset class="time-slots"><legend>Available Arrival Windows</legend><div id="slots"></div></fieldset>${contactFields()}<label>Device / issue<textarea name="issue" rows="3" maxlength="1000" placeholder="Tell us what you need help with"></textarea></label><button class="button">Book Visit</button><p id="visit-error" role="status"></p></form>`);
 const date=$('#date');date.min=iso(new Date());date.value=date.min;
 function slots(){const now=new Date();$('#slots').innerHTML=windows.map(w=>{const start=new Date(date.value+'T'+String(w.start).padStart(2,'0')+':00:00');const unavailable=start<=now||state.bookings.some(b=>b.date===date.value&&b.start===w.start);return `<label class="slot ${unavailable?'unavailable':''}"><input type="radio" name="window" value="${w.start}" required ${unavailable?'disabled':''}>${w.label}${unavailable?' · Unavailable':''}</label>`}).join('')}
 date.onchange=slots;slots();$('#visit').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),day=f.get('date'),start=Number(f.get('window'));if(!day||new Date(day+'T'+String(start).padStart(2,'0')+':00:00')<=new Date()||state.bookings.some(b=>b.date===day&&b.start===start)){slots();$('#visit-error').textContent='Please select an available future window.';return}const id='SV-'+(state.bookings.length+1001);state.bookings.push({id,date:day,start,service:f.get('service')});const display=new Date(day+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});show(`<h2>Your Visit Is Booked</h2><p><strong>${f.get('service')}</strong><br>${display}<br>${windows.find(w=>w.start===start).label}</p><p>Booking reference: <strong>${id}</strong>. Bring your device and any relevant accessories.</p><button data-close class="button">Done</button>`)}}
$('#customer-support').onclick=()=>{show(`<h2>Customer Support</h2><p>Send your question to our team at support@techhubelectronics.com.</p><form id="email-form">${contactFields()}<label>Subject<input name="subject" required maxlength="150"></label><label>Message<textarea name="message" required rows="5" maxlength="3000"></textarea></label><button class="button">Send Message</button></form>`);$('#email-form').onsubmit=e=>{e.preventDefault();show('<h2>Message Received</h2><p>Thank you for contacting TechHub Electronics. Our team will follow up about your question.</p><button data-close class="button">Done</button>')}};
$('#student-info').onclick=()=>{state.studentVerified=false;show(`<h2>Verify Student Savings</h2><p>Complete the demonstration verification to receive 10% off your bag.</p><form id="student-form"><label>College or university<input name="school" required maxlength="100"></label><label>Student email<input name="email" type="email" required placeholder="you@college.edu"></label><label><input type="checkbox" name="enrolled" required> I am currently enrolled.</label><button class="button">Continue to Verification</button><p id="student-result" role="status"></p></form>`);$('#student-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),email=String(f.get('email'));if(!/@[^@]+\.edu$/i.test(email)){$('#student-result').textContent='Enter a valid college .edu email.';return}if(!String(f.get('school')).trim()||!f.get('enrolled'))return;show('<h2>Confirm Your Student Email</h2><p>Demo verification code: <strong>430202</strong>. No email is sent in this assignment.</p><form id="verify-form"><label>Six-digit verification code<input name="code" inputmode="numeric" pattern="[0-9]{6}" required maxlength="6"></label><button class="button">Verify Student Status</button><p id="verify-result" role="status"></p></form>');$('#verify-form').onsubmit=e=>{e.preventDefault();if(new FormData(e.target).get('code')!=='430202'){$('#verify-result').textContent='Incorrect code. Try 430202.';return}state.studentVerified=true;show('<h2>Student Status Verified</h2><p>Your 10% student discount will apply automatically in your bag and checkout during this session.</p><button id="open-verified-bag" class="button">View Bag</button>');$('#open-verified-bag').onclick=bagView}}};
$('#tracking').onclick=()=>{show(`<h2>Order Tracking</h2><p>Enter your order reference, or try TH-DEMO to explore tracking.</p><form id="tracking-form"><label>Order reference<input name="reference" required placeholder="TH-1001"></label><button class="button">Track Order</button></form><div id="tracking-result" role="status"></div>`);$('#tracking-form').onsubmit=e=>{e.preventDefault();const id=new FormData(e.target).get('reference').trim().toUpperCase(),order=id==='TH-DEMO'?{id,status:'Ready for Pickup',items:['Laptop','USB Flash Drive'],fulfillment:'Curbside Pickup'}:state.orders.find(o=>o.id===id);$('#tracking-result').textContent=order?`${order.id}: ${order.status}. ${order.items.join(', ')}. ${order.fulfillment}.`:'We could not find that reference. Check the number and try again.'}};render();

const chatHistory=[{who:'support',text:'Hi! I’m TechHub’s virtual support assistant. Ask about products, pickup, repairs or booking a support visit.'}];
function chatReply(message){const m=message.toLowerCase();if(/book|appointment|schedule|visit/.test(m))return 'Choose Plan a support visit to select your service, date and a two-hour arrival window. You’ll receive a booking reference.';if(/repair|broken|fix|setup|set up|troubleshoot/.test(m))return 'We help with device setup, repairs and troubleshooting. Book a support visit and tell us about your device and issue.';if(/student|discount|college/.test(m))return 'Use Explore student savings to complete student verification and unlock a 10% discount in your bag.';if(/pickup|delivery|shipping/.test(m))return 'Save your selected devices to your bag, then check out with your selected devices and choose curbside pickup, in-store pickup or delivery.';if(/order|track|reference/.test(m))return 'Use Order tracking with your TH order reference. You can also try TH-DEMO to view a ready-for-pickup order.';if(/price|cost|usb|flash/.test(m))return 'USB Flash Drives range from $9–$49, Laptops $299–$1,299, Drones $99–$249 and Smart Home Devices $29–$199. Shop a category to select two devices and click Compare Devices for a closer look.';if(/laptop|gaming|drone|tv|brand|accessor|screen|product/.test(m))return 'Browse our seven categories for devices, accessories and brands. Mobile Accessories includes phone cases, cables, power banks and screen protectors. Save your favorites to your bag.';if(/email|human|agent|contact/.test(m))return 'Choose Customer Support to send an on-site message to support@techhubelectronics.com.';if(/hello|hi\b|thanks|thank/.test(m))return 'Happy to help! What would you like to know about shopping or tech support?';return 'I can help with products, prices, pickup, student discounts, order tracking or support appointments. For a specific question, use Customer Support to message our team.'}
function paintChat(){const log=$('#chat-log');log.innerHTML='';chatHistory.forEach(m=>{const bubble=document.createElement('div');bubble.className='chat-bubble '+m.who;const label=document.createElement('strong');label.textContent=m.who==='support'?'TechHub Assistant':'You';const text=document.createElement('p');text.textContent=m.text;bubble.append(label,text);log.append(bubble)});log.scrollTop=log.scrollHeight}
$('#chat-support').onclick=()=>{show('<h2>Chat With Support</h2><p class="chat-caption">TechHub Virtual Assistant</p><div id="chat-log" role="log" aria-live="polite" aria-label="Support conversation"></div><form id="chat-form"><label>Your message<input id="chat-message" name="message" placeholder="How can we help?" required maxlength="1000" autocomplete="off"></label><button class="button">Send</button></form>');paintChat();$('#chat-form').onsubmit=e=>{e.preventDefault();const input=$('#chat-message'),message=input.value.trim();if(!message)return;chatHistory.push({who:'you',text:message},{who:'support',text:chatReply(message)});paintChat();input.value='';input.focus()}};
$('#appointment').onclick=()=>{
 show(`<h2>Book a Support Visit</h2><p>Choose a service, date and two-hour arrival window.</p><form id="visit"><label>Service<select name="service"><option>Device Setup</option><option>Repair & Troubleshooting</option><option>Extended Warranty Consultation</option></select></label><label>Visit date<input type="date" name="date" id="date" required></label><fieldset class="time-slots"><legend>Available Arrival Windows</legend><div id="slots"></div></fieldset>${contactFields()}<label>Device / issue<textarea name="issue" rows="3" maxlength="1000" placeholder="Tell us what you need help with"></textarea></label><button class="button">Book Visit</button><p id="visit-error" role="status"></p></form>`);
 const date=$('#date');date.min=iso(new Date());date.value=date.min;
 function slots(){const now=new Date();$('#slots').innerHTML=windows.map(w=>{const start=new Date(date.value+'T'+String(w.start).padStart(2,'0')+':00:00');const unavailable=start<=now||state.bookings.some(b=>b.date===date.value&&b.start===w.start);return `<label class="slot ${unavailable?'unavailable':''}"><input type="radio" name="window" value="${w.start}" required ${unavailable?'disabled':''}>${w.label}${unavailable?' · Unavailable':''}</label>`}).join('')}
 date.onchange=slots;slots();$('#visit').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),day=f.get('date'),start=Number(f.get('window'));if(!day||new Date(day+'T'+String(start).padStart(2,'0')+':00:00')<=new Date()||state.bookings.some(b=>b.date===day&&b.start===start)){slots();$('#visit-error').textContent='Please select an available future window.';return}const id='SV-'+(state.bookings.length+1001);state.bookings.push({id,date:day,start,service:f.get('service')});const display=new Date(day+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});show(`<h2>Your Visit Is Booked</h2><p><strong>${f.get('service')}</strong><br>${display}<br>${windows.find(w=>w.start===start).label}</p><p>Booking reference: <strong>${id}</strong>. Bring your device and any relevant accessories.</p><button data-close class="button">Done</button>`)}}
$('#customer-support').onclick=()=>{show(`<h2>Customer Support</h2><p>Send your question to our team at support@techhubelectronics.com.</p><form id="email-form">${contactFields()}<label>Subject<input name="subject" required maxlength="150"></label><label>Message<textarea name="message" required rows="5" maxlength="3000"></textarea></label><button class="button">Send Message</button></form>`);$('#email-form').onsubmit=e=>{e.preventDefault();show('<h2>Message Received</h2><p>Thank you for contacting TechHub Electronics. Our team will follow up about your question.</p><button data-close class="button">Done</button>')}};
$('#student-info').onclick=()=>{state.studentVerified=false;show(`<h2>Verify Student Savings</h2><p>Complete the demonstration verification to receive 10% off your bag.</p><form id="student-form"><label>College or university<input name="school" required maxlength="100"></label><label>Student email<input name="email" type="email" required placeholder="you@college.edu"></label><label><input type="checkbox" name="enrolled" required> I am currently enrolled.</label><button class="button">Continue to Verification</button><p id="student-result" role="status"></p></form>`);$('#student-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),email=String(f.get('email'));if(!/@[^@]+\.edu$/i.test(email)){$('#student-result').textContent='Enter a valid college .edu email.';return}if(!String(f.get('school')).trim()||!f.get('enrolled'))return;show('<h2>Confirm Your Student Email</h2><p>Demo verification code: <strong>430202</strong>. No email is sent in this assignment.</p><form id="verify-form"><label>Six-digit verification code<input name="code" inputmode="numeric" pattern="[0-9]{6}" required maxlength="6"></label><button class="button">Verify Student Status</button><p id="verify-result" role="status"></p></form>');$('#verify-form').onsubmit=e=>{e.preventDefault();if(new FormData(e.target).get('code')!=='430202'){$('#verify-result').textContent='Incorrect code. Try 430202.';return}state.studentVerified=true;show('<h2>Student Status Verified</h2><p>Your 10% student discount will apply automatically in your bag and checkout during this session.</p><button id="open-verified-bag" class="button">View Bag</button>');$('#open-verified-bag').onclick=bagView}}};
$('#tracking').onclick=()=>{show(`<h2>Order Tracking</h2><p>Enter your order reference, or try TH-DEMO to explore tracking.</p><form id="tracking-form"><label>Order reference<input name="reference" required placeholder="TH-1001"></label><button class="button">Track Order</button></form><div id="tracking-result" role="status"></div>`);$('#tracking-form').onsubmit=e=>{e.preventDefault();const id=new FormData(e.target).get('reference').trim().toUpperCase(),order=id==='TH-DEMO'?{id,status:'Ready for Pickup',items:['Laptop','USB Flash Drive'],fulfillment:'Curbside Pickup'}:state.orders.find(o=>o.id===id);$('#tracking-result').textContent=order?`${order.id}: ${order.status}. ${order.items.join(', ')}. ${order.fulfillment}.`:'We could not find that reference. Check the number and try again.'}};render();

const chatHistory=[{who:'support',text:'Hi! I’m TechHub’s virtual support assistant. Ask about products, pickup, repairs or booking a support visit.'}];
function chatReply(message){const m=message.toLowerCase();if(/book|appointment|schedule|visit/.test(m))return 'Choose Plan a support visit to select your service, date and a two-hour arrival window. You’ll receive a booking reference.';if(/repair|broken|fix|setup|set up|troubleshoot/.test(m))return 'We help with device setup, repairs and troubleshooting. Book a support visit and tell us about your device and issue.';if(/student|discount|college/.test(m))return 'Use Explore student savings to complete student verification and unlock a 10% discount in your bag.';if(/pickup|delivery|shipping/.test(m))return 'Save your selected devices to your bag, then check out with your selected devices and choose curbside pickup, in-store pickup or delivery.';if(/order|track|reference/.test(m))return 'Use Order tracking with your TH order reference. You can also try TH-DEMO to view a ready-for-pickup order.';if(/price|cost|usb|flash/.test(m))return 'USB Flash Drives range from $9–$49, Laptops $299–$1,299, Drones $99–$249 and Smart Home Devices $29–$199. Shop a category to select two devices and click Compare Devices for a closer look.';if(/laptop|gaming|drone|tv|brand|accessor|screen|product/.test(m))return 'Browse our seven categories for devices, accessories and brands. Mobile Accessories includes phone cases, cables, power banks and screen protectors. Save your favorites to your bag.';if(/email|human|agent|contact/.test(m))return 'Choose Customer Support to send an on-site message to support@techhubelectronics.com.';if(/hello|hi\b|thanks|thank/.test(m))return 'Happy to help! What would you like to know about shopping or tech support?';return 'I can help with products, prices, pickup, student discounts, order tracking or support appointments. For a specific question, use Customer Support to message our team.'}
function paintChat(){const log=$('#chat-log');log.innerHTML='';chatHistory.forEach(m=>{const bubble=document.createElement('div');bubble.className='chat-bubble '+m.who;const label=document.createElement('strong');label.textContent=m.who==='support'?'TechHub Assistant':'You';const text=document.createElement('p');text.textContent=m.text;bubble.append(label,text);log.append(bubble)});log.scrollTop=log.scrollHeight}
$('#chat-support').onclick=()=>{show('<h2>Chat With Support</h2><p class="chat-caption">TechHub Virtual Assistant</p><div id="chat-log" role="log" aria-live="polite" aria-label="Support conversation"></div><form id="chat-form"><label>Your message<input id="chat-message" name="message" placeholder="How can we help?" required maxlength="1000" autocomplete="off"></label><button class="button">Send</button></form>');paintChat();$('#chat-form').onsubmit=e=>{e.preventDefault();const input=$('#chat-message'),message=input.value.trim();if(!message)return;chatHistory.push({who:'you',text:message},{who:'support',text:chatReply(message)});paintChat();input.value='';input.focus()}};

const chatHistory=[{who:'support',text:'Hi! I’m TechHub’s virtual support assistant. Ask about products, pickup, repairs or booking a support visit.'}];
function chatReply(message){const m=message.toLowerCase();if(/book|appointment|schedule|visit/.test(m))return 'Choose Plan a support visit to select your service, date and a two-hour arrival window. You’ll receive a booking reference.';if(/repair|broken|fix|setup|set up|troubleshoot/.test(m))return 'We help with device setup, repairs and troubleshooting. Book a support visit and tell us about your device and issue.';if(/student|discount|college/.test(m))return 'Use Explore student savings to check your college .edu email and ask about student discounts at pickup.';if(/pickup|delivery|shipping/.test(m))return 'Save your selected categories to your bag, then request your items and choose curbside pickup, in-store pickup or delivery.';if(/order|track|reference/.test(m))return 'Use Order tracking with your TH request reference. You can also try TH-DEMO to view a ready-for-pickup order.';if(/price|cost|usb|flash/.test(m))return 'USB Flash Drives range from $9–$49, Laptops $299–$1,299, Drones $99–$249 and Smart Home Devices $29–$199. Select categories and click Compare selected for a closer look.';if(/laptop|gaming|drone|tv|brand|accessor|screen|product/.test(m))return 'Browse our seven categories for devices, accessories and brands. Mobile Accessories includes phone cases, cables, power banks and screen protectors. Save your favorites to your bag.';if(/email|human|agent|contact/.test(m))return 'Choose Customer Support to send an on-site message to support@techhubelectronics.com.';if(/hello|hi\b|thanks|thank/.test(m))return 'Happy to help! What would you like to know about shopping or tech support?';return 'I can help with products, prices, pickup, student discounts, order tracking or support appointments. For a specific question, use Customer Support to message our team.'}
function paintChat(){const log=$('#chat-log');log.innerHTML='';chatHistory.forEach(m=>{const bubble=document.createElement('div');bubble.className='chat-bubble '+m.who;const label=document.createElement('strong');label.textContent=m.who==='support'?'TechHub Assistant':'You';const text=document.createElement('p');text.textContent=m.text;bubble.append(label,text);log.append(bubble)});log.scrollTop=log.scrollHeight}
$('#chat-support').onclick=()=>{show('<h2>Chat With Support</h2><p class="chat-caption">TechHub Virtual Assistant</p><div id="chat-log" role="log" aria-live="polite" aria-label="Support conversation"></div><form id="chat-form"><label>Your message<input id="chat-message" name="message" placeholder="How can we help?" required maxlength="1000" autocomplete="off"></label><button class="button">Send</button></form>');paintChat();$('#chat-form').onsubmit=e=>{e.preventDefault();const input=$('#chat-message'),message=input.value.trim();if(!message)return;chatHistory.push({who:'you',text:message},{who:'support',text:chatReply(message)});paintChat();input.value='';input.focus()}};
